version: '3'
services:
  client:
    build: 
      context: ./client
    volumes:
      - ./client/src:/src
    tty: true
    container_name: client

  server:
    build:
      context: ./server
    volumes:
      - ./server/src:/src
    tty: true
    container_name: server

